"""initial

Revision ID: a45a063e970e
Revises: 
Create Date: 2026-06-06 04:09:31.994411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45a063e970e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chw_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chw_responded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('community_health_workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_experience', sa.String(length=30), nullable=True))

    with op.batch_alter_table('community_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_chw', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('chw_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_replies', schema=None) as batch_op:
        batch_op.drop_column('chw_name')
        batch_op.drop_column('is_chw')

    with op.batch_alter_table('community_health_workers', schema=None) as batch_op:
        batch_op.drop_column('years_experience')
        batch_op.drop_column('qualification')

    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_column('chw_responded_at')
        batch_op.drop_column('chw_note')

    # ### end Alembic commands ###
